{
 "title": "Laagheidseweg 15A Energie",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Electra Actueel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "pwr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Actueel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Nm3" } },
   "targets": [
    {
     "measurement": "gas_actuals",
     "query": "SELECT \"gas_m3_hr\" FROM \"gas_actuals\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gas_m3_hr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elektra per dag",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT ((SUM(\"pwr\" )/ 60  / 1000) * 0.25)  FROM \"system\" WHERE $timeFilter group by time(1d)"
    }
   ]
  },
  {
   "title": "Gas per dag",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT ((SUM(\"gas_m3_hr\")/12) * 0.88) FROM \"gas_actuals\" WHERE $timeFilter group by time(1d)"
    }
   ]
  }
 ]
}